version: "3.7"
services:
  #PHP Service
  role_permission:
    build:
      args:
        user: zamshedarifin
        uid: 1000
      context: .
      dockerfile: .docker/Dockerfile
    image: role_permission
    restart: unless-stopped
    working_dir: /var/www/
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - role_permission_network

  #MySQL Service
  role_permission_db:
    image: mysql:8.0
    container_name: role_permission_db
    restart: unless-stopped
    ports:
      - "${DOCKER_DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - role_permission_mysql_data:/var/lib/mysql
    networks:
      - role_permission_network

  #Nginx Service
  role_permission_nginx:
    image: nginx:alpine
    container_name: role_permission_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "${DOCKER_APP_PORT}:80"
      - "${DOCKER_APP_SSL_PORT}:443"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - role_permission_network
  # phpmyadmin service
  role_permission_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    container_name: role_permission_phpmyadmin
    depends_on:
      - role_permission_db
    ports:
      - "${DOCKER_PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: role_permission_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 100M
    networks:
      - role_permission_network

  role_permission_redis_cache:
    image: redis:alpine
    restart: always
    container_name: role_permission_redis_cache
    ports:
      - '${DOCKER_REDIS_PORT}:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - role_permission_cache:/data
    networks:
      - role_permission_network

#Docker Networks
networks:
  role_permission_network:
    driver: bridge

#Volumes
volumes:
  role_permission_mysql_data:
  role_permission_cache:
